### ISSUE TITLE
Allow setting object expiration (X-Delete-After, X-Delete-At Header on PUT)

### ISSUE THREAD

**Issue by JohannesRudolph** [sapcc/concourse-swift-resource#3]
Our build pipelines produce quite a few GBs worth of artifacts a day. It would be awesome if we could specify object retention policies in our pipelines via concourse-swift-resource. All that's needed is wiring a `delete-at` or `delete-after` optional `params` from the resource config in the pipeline through to the PUT call (see https://developer.openstack.org/api-ref/object-storage/?expanded=create-or-replace-object-detail).

That's probably here: https://github.com/sapcc/concourse-swift-resource/blob/master/pkg/resource/out.go#L70

I haven't played with go yet, so I don't feel all too confident to develop a PR (yet). Would you consider implementing this?

**Comment by databus23** [comment]
I'm not sure this plays well with the general concept of resources in concourse. A version of a resource is not supposed to go away once it is created (via `put`). Once concourse has discovered a version I believe the general assumption is that this version can be fetched by another task at any time in the future.

If you want to publish temporary artefacts to swift maybe its better to do so in a task and not in a resource?

**Comment by JohannesRudolph** [comment]
It's optional, so in any case it doesn't force users to violate that assumption of concourse when they don't want to (e.g. expiration is of course off by default). 

Concourse has many "ephemeral" types of resource already, e.g. all kinds of status notifiers like slack, bitbucket etc. so I don't think this is a major problem. And at the end it's entirely within the user's control. What do you reckon?

**Comment by databus23** [comment]
I think adding `delete-after` is straight forward. for `delete-at` the value would need to point to a file where the timestamp is read from. Having static  value for `delete-at` is not that useful, would you agreee?

**Comment by JohannesRudolph** [comment]
Yes that makes sense. Thanks for considering to add this!

Am 01.08.2017 4:14 PM schrieb "Fabian Ruff" <notifications@github.com>:

**Comment by JohannesRudolph** [comment]
Hi @databus23 any news on this? Happy to give this a shot with our Meshcloud Swift.
